export const THEMES = {
  light: {
    id: 'light',
    name: 'Sáng (Clean Light)',
    appBg: 'bg-slate-100',
    pageBg: 'bg-slate-50',
    cardBg: 'bg-white',
    cardBorder: 'border-slate-200',
    cardShadow: 'shadow-sm shadow-slate-200/50',
    textPrimary: 'text-slate-900',
    textSecondary: 'text-slate-600',
    textMuted: 'text-slate-400',
    subtleBg: 'bg-slate-100/80',
    subtleBorder: 'border-slate-200',
    tableHeaderBg: 'bg-slate-100',
    tableHeaderBorder: 'border-slate-200',
    tableRowHover: 'hover:bg-slate-50',
    tableBorder: 'border-slate-200/80',
    chart: {
      bg: '#ffffff',
      text: '#334155',
      split: '#f1f5f9',
      border: '#cbd5e1',
      tooltipBg: '#ffffff',
      tooltipBorder: '#cbd5e1',
      tooltipText: '#0f172a',
      dataZoomBg: '#f8fafc',
      dataZoomFiller: 'rgba(56, 189, 248, 0.2)'
    }
  },
  paper: {
    id: 'paper',
    name: 'Giấy Báo Cáo (Paper)',
    appBg: 'bg-stone-200/60',
    pageBg: 'bg-[#faf8f5]',
    cardBg: 'bg-white',
    cardBorder: 'border-stone-200',
    cardShadow: 'shadow-sm shadow-stone-200/60',
    textPrimary: 'text-stone-900',
    textSecondary: 'text-stone-600',
    textMuted: 'text-stone-400',
    subtleBg: 'bg-stone-100/70',
    subtleBorder: 'border-stone-200',
    tableHeaderBg: 'bg-stone-100',
    tableHeaderBorder: 'border-stone-200',
    tableRowHover: 'hover:bg-stone-50',
    tableBorder: 'border-stone-200/70',
    chart: {
      bg: '#ffffff',
      text: '#44403c',
      split: '#f5f5f4',
      border: '#d6d3d1',
      tooltipBg: '#ffffff',
      tooltipBorder: '#d6d3d1',
      tooltipText: '#1c1917',
      dataZoomBg: '#fafaf9',
      dataZoomFiller: 'rgba(120, 113, 108, 0.2)'
    }
  },
  slate: {
    id: 'slate',
    name: 'Tối Sắc Nét (Dark Slate)',
    appBg: 'bg-slate-950',
    pageBg: 'bg-[#0f172a]',
    cardBg: 'bg-slate-900',
    cardBorder: 'border-slate-800',
    cardShadow: 'shadow-xl shadow-black/40',
    textPrimary: 'text-white',
    textSecondary: 'text-slate-300',
    textMuted: 'text-slate-400',
    subtleBg: 'bg-slate-950/60',
    subtleBorder: 'border-slate-800',
    tableHeaderBg: 'bg-slate-950',
    tableHeaderBorder: 'border-slate-800',
    tableRowHover: 'hover:bg-slate-800/50',
    tableBorder: 'border-slate-800/80',
    chart: {
      bg: '#0f172a',
      text: '#cbd5e1',
      split: '#1e293b',
      border: '#334155',
      tooltipBg: 'rgba(15, 23, 42, 0.95)',
      tooltipBorder: '#475569',
      tooltipText: '#f8fafc',
      dataZoomBg: '#0f172a',
      dataZoomFiller: 'rgba(56, 189, 248, 0.15)'
    }
  },
  midnight: {
    id: 'midnight',
    name: 'Đen Tuyệt Đối (OLED Black)',
    appBg: 'bg-black',
    pageBg: 'bg-black',
    cardBg: 'bg-neutral-950',
    cardBorder: 'border-neutral-800',
    cardShadow: 'shadow-xl shadow-black',
    textPrimary: 'text-white',
    textSecondary: 'text-neutral-300',
    textMuted: 'text-neutral-400',
    subtleBg: 'bg-neutral-900/60',
    subtleBorder: 'border-neutral-800',
    tableHeaderBg: 'bg-neutral-900',
    tableHeaderBorder: 'border-neutral-800',
    tableRowHover: 'hover:bg-neutral-900/60',
    tableBorder: 'border-neutral-800/80',
    chart: {
      bg: '#000000',
      text: '#e5e5e5',
      split: '#1f1f1f',
      border: '#404040',
      tooltipBg: 'rgba(23, 23, 23, 0.95)',
      tooltipBorder: '#525252',
      tooltipText: '#ffffff',
      dataZoomBg: '#171717',
      dataZoomFiller: 'rgba(56, 189, 248, 0.2)'
    }
  }
};
